PromoteCommands:
- perm player %s addgroup friendly
PromoteAnnouncements:
- '%s was promoted to Friendly!'
- 'Everybody, welcome %s to the fold!'
- '%s accepted the rules and ranked up.'
- 'A new player has joined Cavetale: %s!'
- '%s joined Cavetale.'
- 'New arrival: %s.'
- 'Say hello to %s!'
