FromGroup: Guest
ToGroup: Friendly
Announce: false
Rules:
- Server language is &aEnglish&r.
- No &agriefing&r, &astealing&r, or &aspamming&r.
- No &aoffensive skins&r, &abuilds&r, or &aplayer names&r.
- Treat other players with &arespect&r.
- Do not take advantage of &aglitches&r.
- No unfair &amods&r or &aresource packs&r.
- Do not cause unreasonable &alag&r.
- No &aadvertising&r.
