PromoteCommands:
- perm player %s addgroup friendly
Promotion:
- 'Welcome to Cavetale! Please type §e/newb'
PromoteAnnouncements:
- '§a%s was promoted to Friendly!'
- '§aEverybody, welcome %s to the fold!'
- '§a%s accepted the rules and ranked up.'
- '§aA new player has joined Cavetale: %s!'
- '§a%s joined Cavetale.'
- '§aNew arrival: %s.'
