PromoteAnnouncements:
- '%s was promoted to Tier 1!'
- 'Everybody, welcome %s to the fold!'
- '%s accepted the rules and ranked up.'
- 'A new player has joined Cavetale: %s!'
- '%s joined Cavetale.'
- 'New arrival: %s.'
- 'Say hello to %s!'
