name: Rules
description: Display rules and allow accepting them in exchange for a promotion.
author: StarTux
version: 0.1
api-version: 1.13
website: https://cavetale.com
main: com.winthier.rules.RulesPlugin
depend: [Chat]
softdepend: []
commands:
  rules:
    description: Rules
    usage: /rules
    permission: rules.rules
permissions:
  rules.rules:
    description: View and accept the rules
    default: true
  rules.admin:
    description: Perform administrative tasks
    default: op
